on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt'

      - name: Install OpenSSL
        run: |
          brew install openssl@3
          export PATH="/usr/local/opt/openssl@3/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt git+https://github.com/Radekyspec/PyQtDarkTheme.git@main

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: startLive-qt.py
          mode: app
          enable-plugins: pyside6
          noinclude-setuptools-mode: "nofollow"
          noinclude-pytest-mode: "nofollow"
          noinclude-unittest-mode: "nofollow"
          include-data-dir: "resources=resources"
          deployment: true
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
